---
- hosts: 
    - k8s
  become: yes
  tasks:
  - name: ping
    ping:

  # - name: shutdown
  #   command: /sbin/shutdown -h now
  #   ignore_errors: yes
  # - name: leave cluster
  #   shell: kubeadm reset -f
  # - name: rm -rf node_joined.txt
  #   shell: rm -rf node_joined.txt
  # - name: systemctl disable firewalld
  #   service:
  #     name: firewalld
  #     state: stopped
  #     enabled: no
  # - name: Unconditionally reboot the machine with all defaults
  #   reboot:


- hosts: 
    - workers
    - masters
  become: yes
  tasks:
    - name: ping
      ping:
    - name: leave cluster
      shell: kubeadm reset -f
    - name: rm -rf cluster_initialized.txt
      shell: rm -rf /root/cluster_initialized.txt
    - name: rm -rf cluster_initialized.txt
      shell: rm -rf /root/node_joined.txt

    - name: net-tools install
      yum: 
        name: net-tools
        state: latest


    - name:
      shell: systemctl stop kubelet
    - name:
      shell: systemctl stop docker
    - name:
      shell: rm -rf /var/lib/cni/
    - name:
      shell: rm -rf /var/lib/kubelet/*
    # - name:
    #   shell: rm -rf /etc/cni/
    # - name:
    #   shell: ifconfig cni0 down
    # - name:
    #   shell: ifconfig flannel.1 down
    # - name:
    #   shell: ifconfig docker0 down

    - name: start Docker
      service:
        name: docker
        state: started
        enabled: yes
