- hosts: k8s-m
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --apiserver-advertise-address=192.168.10.80 --apiserver-cert-extra-sans=192.168.10.80 --node-name k8s-m --pod-network-cidr=172.16.0.0/16

    - name: create .kube directory
      become: yes
      become_user: root
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      become: yes
      become_user: root
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes
        owner: root

    - name: taint master node
      shell: kubectl taint nodes k8s-m node-role.kubernetes.io/master-

  # calico network
    - name: install Calico Pod network
      shell: kubectl apply -f https://docs.projectcalico.org/v3.9/manifests/calico.yaml

# # flannel network
#     - name: install flannel Pod network
#       shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml


# kubeadm join 192.168.10.80:6443 --token qgvnkn.wf7jwifhwlp4k81d \
#     --discovery-token-ca-cert-hash sha256:ab3beb43771f6c0bd51854847a73ab7e489994cf7ee7124b00f3722910b349e5 \
#     --node-ip=192.168.10.81


# kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-legacy.yml
# kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml
# error: unable to recognize "": no matches for kind "" in version ""