---
# - name:   ping k8s
#   hosts:
#     - masters
#     - workers
#   become: no

#   tasks:
#   # - name: ping
#   #   ping:
#   #   ignore_unreachable: yes
#   #   ignore_errors: yes

- hosts: server
  become: yes
  tasks:

  - name: ping
    ping:


  - name: clone k8s-m from clear-k8s-m
    shell: virt-clone --original clear-k8s-m --name k8s-m --auto-clone
  - name: clone k8s-m from clear-k8s-n1
    shell: virt-clone --original clear-k8s-n1 --name k8s-n1 --auto-clone
  - name: clone k8s-m from clear-k8s-n2
    shell: virt-clone --original clear-k8s-n2 --name k8s-n2 --auto-clone

  - name: start vm k8s-m
    virt:
      name: k8s-m
      state: running
  - name: start vm k8s-n1
    virt:
      name: k8s-n1
      state: running
  - name: start vm k8s-n2
    virt:
      name: k8s-n2
      state: running
  - name: wait to start
    pause:
      seconds: 20

