---
- name: install nginx
  hosts: gogs_ws
  become: yes

  tasks:
    - name: ping
      ping:

    - name: install epel-release, git, wget 1
      yum:
        name:
          - epel-release
          - git
        state: present

    - name: groupadd git 2
      group:
        name: git
        state: present

    - name: Creates directory 3
      file:
        path: /opt/gogs
        state: directory

    - name: useradd 4
      user:
        name: git
        state: present
        group: git
        shell: /bin/nologin
        home: /opt/gogs

    - name: unzip gogs 5
      unarchive:
        src: /Users/triaz/Documents/GitHub/my-ansible-tools/files/gogs.tar.gz
        dest: /opt

    - name: chown git:git gogs
      file:
        path: /opt/gogs
        state: directory
        recurse: yes
        owner: git
        group: git

    - name: copy service file 6
      copy:
        src: /Users/triaz/Documents/GitHub/my-ansible-tools/files/gogs.service
        dest: /etc/systemd/system/gogs.service

    - name: systemctl daemon-reload 7
      systemd:
        daemon_reload: yes

    - name: start gogs service 8
      service: 
        name: gogs
        state: started
        enabled: yes

    # - name: firewall-cmd --permanent --zone=public --add-port=3000/tcp 9
    #   firewalld: port=3000/tcp permanent=true state=enabled immediate=yes
    # - name: start gogs service 10
    #   service: name=firewalld state=reloaded

