---
- name:   setup swarm
  hosts:  swarm
  become: yes

  tasks:
  - name: ping
    ping:
  
  - name: yum-utils
    yum:
      name:
      - yum-utils
  - name: device-mapper-persistent-data
    yum:
      name:
      - device-mapper-persistent-data
  - name: lvm2
    yum:
      name:
      - lvm2
  - name: epel-release
    yum:
      name:
      - epel-release
  # - name: python-docker
  #   yum:
  #     name:
  #     - python-docker
  - name: Add Docker repo
    shell: yum-config-manager     --add-repo     https://download.docker.com/linux/centos/docker-ce.repo

  - name: install  docker-ce
    yum:
      name:
      - docker-ce
  - name: install  docker-ce-cli
    yum:
      name:
      - docker-ce-cli
  - name: install  containerd.io
    yum:
      name:
      - containerd.io
  - name: install python docker
    yum:
      name: 
      - python-docker

  - name: enable service
    service:
      name: docker
      state: started
      enabled: yes
  - name: add vagrant user to docker group
    user:
      name: vagrant
      group: docker

- name: hostname change master
  hosts: master
  become: yes

  tasks:
  - name: hostname change to swarm-master
    hostname:
      name: swarm-master

- name: hostname change node
  hosts: node
  become: yes

  tasks:
  - name: hostname change to swarm-node
    hostname:
      name: swarm-node

- name:   reboot swarm
  hosts:  swarm
  become: yes

  tasks:
  - name: Reboot the server
    tags: reboot
    become: yes
    become_user: root
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0
  - name: Wait for the reboot to complete if there was a change.
    wait_for_connection:
      connect_timeout: 10
      sleep: 5
      delay: 5
      timeout: 300
