---
- name: swarm init master
  hosts: master
  become: yes

  tasks:

  - name:
    shell: docker swarm leave --force

  - name: Init a new swarm with default parameters
    docker_swarm:
      state: present
  - name: Inspect swarm
    docker_swarm_info:
  - name: token
    shell: docker swarm join-token worker | grep token
  #   register: Token
  # - debug: msg={{Token.output}}
