---
- name: swarm node join
  hosts: node
  become: yes

  tasks:

  - name: Add nodes
    docker_swarm:
      state: join
      advertise_addr: 192.168.22.32
      join_token: SWMTKN-1-4h14n57lmyilpvq80g580yib3vn4bbgiz7bgs71y581iv3a4ck-65rfc8jeu9he81sl7ikl2l3ko
      remote_addrs: [ '192.168.22.31:2377' ]