---
- name:   setup swarm
  hosts:  master
  become: yes

  tasks:
  - name: Get info on Docker Swarm
    docker_swarm_info:
      join-token: worker
    register: result

  - name: Inform about basic flags
    debug:
      msg: |
        Was able to talk to docker daemon: {{ result.output }}
