---
- name: get join_token
  hosts: docker-swarm-head
  become: yes
  
  tasks:
  - name: Inspect swarm
    docker_swarm:
      state: inspect
    register: swarm_info
  - name: output
    debug:
      var: swarm_info.swarm_facts.JoinTokens.Worker








- name: swarm node join
  hosts: node
  become: yes

  tasks:

  - name: output hostvars['docker-swarm-head'].ansible_eth1.ipv4.address
    debug:
      msg: "{{  hostvars['docker-swarm-head'].ansible_eth1.ipv4.address }}"
  - name: output token
    debug:
      msg: "{{ hostvars['docker-swarm-head']['swarm_info'].swarm_facts.JoinTokens.Worker }}"
  - name: output node ip
    debug:
      msg: "{{ hostvars[inventory_hostname].ansible_eth1.ipv4.address }}"
  - name: Add nodes
    docker_swarm:
      state: join
      advertise_addr: "{{ hostvars[inventory_hostname].ansible_eth1.ipv4.address }}" 
      join_token: "{{ hostvars['docker-swarm-head']['swarm_info'].swarm_facts.JoinTokens.Worker }}"
      remote_addrs: [ "{{ hostvars['docker-swarm-head'].ansible_eth1.ipv4.address }}" ]


