---
- name:    Config node1
  hosts:   galera1
  become: yes

  tasks:
  - name: start galera_new_cluster
    shell: galera_new_cluster

- name:    Config node2
  hosts:   galera2
  become: yes

  tasks:
  - name: start_mariadb 2
    service: name=mariadb state=started 

- name:    Config node3
  hosts:   galera3
  become: yes

  tasks:
  - name: start_mariadb 3
    service: name=mariadb state=started 
