---
- name: Stopping nodes 3
  hosts: galera3
  become: yes

  tasks:
  
  - name: check whether the node is up to date
    shell: mysql -u root -e "SHOW STATUS LIKE 'wsrep_local_state_comment'"
  
  - name: stop mysql service 3
    service: name=mariadb state=stopped

- name: Stopping nodes 2
  hosts: galera2
  become: yes

  tasks:
  - name: check whether the node is up to date
    shell: mysql -u root -e "SHOW STATUS LIKE 'wsrep_local_state_comment'"
  
  - name: stop mysql service 2
    service: name=mariadb state=stopped
        
- name: Stopping nodes 1
  hosts: galera1
  become: yes

  tasks:
  - name: check whether the node is up to date
    shell: mysql -u root -e "SHOW STATUS LIKE 'wsrep_local_state_comment'"
  
  - name: stop mysql service 1
    service: name=mariadb state=stopped
            